name: Hello World
on: [push]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        steps:
          - name: print Hello
          - run: echo "Hello from github actions!"